server:
  port: 8080

publicKey: MIICWwIBAAKBgQDQP2LY/DO8arTxS8IaUgaYYX0qQVy4dFPljtFBIqiy0g74GTD5
  UnDAsoTEIdbKonxqDFnn4e0zx5tVP5Ge1Gw45l2VixBpnwMR9Q0xAte5Aoc2W/SQ
  54OnuPSXGekydhJC8Kb/Mn3zLOLBP34Z/1N9FTn6fz+OfrFjaAG9KWACgwIDAQAB
  AoGARIo4PHZ1iLQOLcTjc8o/hXPAwGGW5NbUrh9dW/TOVVyxtJKF/elWVvXqoKsK
  iNMF49mA1cMUURCHXX14ri/4FgIcy45oKtI/MuGEkOfZBbbezm3movHcNUfxNaI/
  QzF9ZsCy6Xij5bGdaKSjkN9/GR8yXHKDlYu0L8CGVgMDkBECQQDuFLK1T+sUOgGf
  UgscbGbRO2XtzqDiJliVHIKbzdn3MrDSBZdJCAwt8IA1emniKaAKDYCzkifAwWkn
  XuQHNKJ9AkEA3+vdsY6Jq3JjSTp3bj3GjQ5SHnmrp0hJ5HYZoEz8V0YD75CNBIch
  lXKMNmxZRcb+LTHMCGU3qCZ7wFaflGtI/wJAWbfxFISWaRvm6pwnVcHACU8h/Tjl
  xfN/ZEnHKmGrpw0yNyMmPL5MoK9GEWEdL75R8hfejU0hr/Dy6IRI2DJMnQJAHY36
  ItdXYGOmqyGmZcyNikyblh4lA91Ms3TLCRdgLvy0xEfl9PUI/7qwuvYuCkGrhreN
  4IXLhMwfhVFpmqNWbQJAVFGaycKAI0TtFRawm+pj2OuZzirAasgvnVf1bV4plpma
  zT8Vdy7y958NoOjA66RipUhwdzIyyFuNfxjCU0AlQQ==
